### ISSUE TITLE
Get RSA public key string

### ISSUE THREAD

**Issue by yuval-netanel** [hohl/MIHCrypto#20]
I want to send the public key to the server. 
This is how I tried to get the public key string, but it returns null:

```objective-c
 MIHRSAKeyFactory *factory = [[MIHRSAKeyFactory alloc] init];
 factory.preferedKeySize = MIHRSAKey512;
 MIHKeyPair *keyPair = [factory generateKeyPair];
  
 NSString *publicKeyStr = [keyPair.public description];
 NSLog(@"%@", publicKeyStr);// logs null

 NSData *data = [keyPair.public dataValue];
 publicKeyStr = [[NSString alloc] initWithData:data encoding:NSUTF8StringEncoding];
 NSLog(@"%@", publicKeyStr);// logs null
``` 

Any suggestions?

**Comment by askxlogic** [comment]
@hohl I have same issue. I found that reason of it is wrong encoding of NSData that return method
``` Objective-c
[keyPair.public dataValue];
```
I think that this issue and [this issue](https://github.com/hohl/MIHCrypto/issues/21) is same.

**Comment by hohl** [comment]
You mean, using `NSDataBase64DecodingIgnoreUnknownCharacters` fixes this issue?

**Comment by askxlogic** [comment]
For fixing this issue change method
```Objective-c
- (NSString *)description
{
    return [[NSString alloc] initWithData:[self dataValue] encoding:NSUTF8StringEncoding];
}
```
to
```Objective-c
- (NSString *)description
{
    return [[self dataValue] base64EncodedStringWithOptions:NSDataBase64EncodingEndLineWithLineFeed];
}
```
in **MIHRSAPublicKey.m**

**Comment by askxlogic** [comment]
I am sorry. It just looks like similar bugs. Everything working for me without ```NSDataBase64DecodingIgnoreUnknownCharacters```

**Comment by hohl** [comment]
`description` is for debugging anyway. However I thought this issue is about not being able to generate public keys? If it's about the `description` output I may need to have second look at it.

**Comment by yuval-netanel** [comment]
Sorry if it wasn't clear, but it's about the `description` output.

**Comment by hohl** [comment]
Oh dear. Since the `description` field has been added for testing purposes I've forgotten about the unit tests for, I'm sorry.

I'll fix it immeditley, this should do the job:

    - (NSString *)description
    {
        return [[self dataValue] MIH_base64EncodedString];
    }
