### ISSUE TITLE
how can I install MIHCrypto without using Cocoapods

### ISSUE THREAD

**Issue by lwsitachi** [hohl/MIHCrypto#22]
I was building a framework by a template named "iOS-Universal-Framework"(https://github.com/kstenerud/iOS-Universal-Framework)   I can add some other 3rd-party static library in my framework project.But I don't know how to add your code in it.So I just want to know that if I can build your source code into a static library without using Cocoapods.

**Comment by hohl** [comment]
MIHCrypto only has one dependency, which is (you might have guessed it already) OpenSSL. So all you need todo is:

 - copy all files into your project
 - build OpenSSL for iOS and link it against your framework

However this is quite a heavy task comparing to just add a dependency via CocoaPods. (If there isn't any good reason not to use CocoaPods don't try to ignore this helpful tool!)

**Comment by lwsitachi** [comment]
okay,thx
