### ISSUE TITLE
Decrypting RSA

### ISSUE THREAD

**Issue by tillmannheigel** [hohl/MIHCrypto#23]
Hi I've got the same bug as in #17 here ("MIHCrypto", "~> 0.3.2"). These are my lines of code:

    NSString *encrypted_text = @"BdhFH0sd7e9DExiCd50Ykh4spm2BX126skjJ1o8HHjKsN+J7r9IoI9kbB9AAacEpJsAfyesiJsq5gDBhQtcNbB6l88aSgPrEoVwR9ilzuzVcv1q3J1dxs4uIEMuhzoWT+R8//dD2jDdXPyFsdGWJc10CEizPFKpmy2jWhvU8CVs=";
    NSBundle *myBundle = [NSBundle mainBundle];
    NSString *privateKeyPath= [myBundle pathForResource:@"rsa_1024_priv" ofType:@"pem"];    
    NSData *privateKeyData = [[NSFileManager defaultManager] contentsAtPath:privateKeyPath];
    MIHRSAPrivateKey *privateKey = [[MIHRSAPrivateKey alloc] initWithData:privateKeyData];
    NSError *decryptionError = nil;

    // decryption
    NSData *encData = [encrypted_text dataUsingEncoding:NSUTF8StringEncoding];
    NSData *decryptedEncData = [privateKey decrypt:encData error:&decryptionError];
    NSString* decryptedText = [[NSString alloc] initWithData:decryptedEncData encoding:NSUTF8StringEncoding]; // iOS 7+, by iOS Core API

    if(decryptionError){
        DDLogDebug(@"error: %@",[encryptionError localizedDescription]);
    }
    DDLogDebug(@"decrypted: %@",decryptedEncData);

The problem is the same as in #17:

error: OpenSLL internal error! (Code=67522668,Description=error:0406506C:rsa routines:RSA_EAY_PRIVATE_DECRYPT:data greater than mod len)

Do you have any Idea??

**Comment by hohl** [comment]
As mentioned in the other issue: The data you want to encrypt is too large. RSA only can encrypt data up to the size of it's key.

You should read about the pros and cons of RSA. Then you will notice that RSA isn't designed for encrypting big data sets. The main purposes of RSA are:
 - encrypting keys of other cryptographic approaches (for ex. for safely exchanging them over the internet )
 - encrypting hash sums (for validation and authentication purposes)
