### ISSUE TITLE
RSA encrypting data which is larger then the key causes an uninformative error message

### ISSUE THREAD

**Issue by hohl** [hohl/MIHCrypto#24]
*Using RSA with large blocks of data seems to be a common issue. Some wrappers handle this by splitting the data into smaller blocks and encrypting every block separately. But since RSA isn't intended to encrypt large blocks of data this won't be implemented in this wrapper. (Better combine RSA with something like AES if you need features of both worlds.)*

At the moment (RELEASE-0.3.2) the error message is:
   
     error: Error Domain=MIHOpenSSLErrorDomain Code=67522668 "OpenSLL internal error! (Code=67522668,Description=error:0406506C:rsa routines:RSA_EAY_PRIVATE_DECRYPT:data greater than mod len)" UserInfo=0x170275700 {NSLocalizedDescription=OpenSLL internal error! (Code=67522668,Description=error:0406506C:rsa routines:RSA_EAY_PRIVATE_DECRYPT:data greater than mod len)}

But it would be more informative if it would be something more descriptive.

Writing some sample and/or wiki page on how to use AES and RSA in combination would be a good idea too.

**Comment by hohl** [comment]
Related issues: #23, #17

**Comment by dvidlui** [comment]
Hi Michael,
Can you let me know how to use RSA in combination with AES in current MIHCrypto ios library?

**Comment by hohl** [comment]
There is no automated way, but it's quite simple.

*A does:* Generate a random key for use with AES
*B does:* Generate a private/public key pair for RSA (see `MIHRSAKeyFactory`)
*A does:* Download the public key of A (it's up to yours how to transport the key, maybe via HTTP?)
*A does:* Encrypt the generated AES key via the public RSA key of B (see `MIHRSAPublicKey`)
*A does:* Send the encrypted AES key to B
*A does:* Encrypt the data with the shared AES key and send it to B (see `MIHAESSymmetricKey`)
*B does:* Receive the data and decrypt it with the shared AES key (see `MIHAESSymmetricKey` again)

**Comment by dvidlui** [comment]
Thank you for your detailed instructions.
