### ISSUE TITLE
<Foundation/Foundation.h> is lost

### ISSUE THREAD

**Issue by askxlogic** [hohl/MIHCrypto#26]
MIHCripto don't have #import <Foundation/Foundation.h> in root header. For example MIHCoding.h is NSObject protocol child. But in this file I can't find any way for loading <Foundation/Foundation.h>. I have a lot of build errors.

**Comment by hohl** [comment]
Do you use CocoaPods for dependency management or do you just copy all source files into your project?

**Comment by askxlogic** [comment]
I use CocoaPods.
My Podfile:
```
# Uncomment this line to define a global platform for your project
platform :ios, '6.0'

pod "MIHCrypto", "~> 0.3.2"

target 'askCrypt' do

end

target 'askCryptTests' do

end
```

**Comment by askxlogic** [comment]
Adding string 
```objective-c
#import <Foundation/Foundation.h>
```
in file  **MIHCoding.h** solve this problem.

**Comment by hohl** [comment]
Thanks, I may add it in next release. Most developers don't seem to need it, however it won't hurt anybody too.

**Comment by hohl** [comment]
Sorry, would like to keep it open as a reminder for myself to add the `#import`.
