### ISSUE TITLE
issue with cryptlib.a

### ISSUE THREAD

**Issue by aetsyss** [hohl/MIHCrypto#37]
Hi,
could you pls help me to resolve the issue - the real device works perfect, but when I'm trying to run my project with this lib on a Simulator there is an error:
...MyProject/Pods/OpenSSL-Universal/lib-ios/libcrypto.a(cryptlib.o), building for iOS simulator, but linking in object file built for OSX, for architecture x86_64

Thank you!

**Comment by hohl** [comment]
Are you using the most recent Xcode build? If yes, please try if this issue still occurs to you with release 0.4.1.

**Comment by aetsyss** [comment]
Hi,
now it works even with 0.4.0. I don't know what was the problem. Perhaps the latest xcode version solved the problem. Thank you for your help and for you lib!!
