### ISSUE TITLE
Can't compile any app

### ISSUE THREAD

**Issue by dtokos** [hohl/MIHCrypto#41]
Hello,
I'm installing using MIHCrypto this pod file:

target 'MIHCryptoProject' do
  pod 'MIHCrypto', '~> 0.4'
end

and when i compile the project i get this error:
linker command failed with exit code 1

duplicate symbol _llvm.embedded.module in:
    /Users/dtokos/Documents/dobro/Xcode/fsjgh/Pods/OpenSSL-Universal/lib-ios/libcrypto.a(bio_lib.o)
    /Users/dtokos/Documents/dobro/Xcode/fsjgh/Pods/OpenSSL-Universal/lib-ios/libcrypto.a(gost_sign.o)
ld: 888 duplicate symbols for architecture x86_64

I'm using Xcode 6.2 on OSX 10.9.5

Can you help me? I'm new to Cocoapods, maybe it's my fault. Anyway thanks for help.

Have a nice day

**Comment by hohl** [comment]
Sounds like an issue related [to this repository. OpenSSL-Universal](https://github.com/krzyzanowskim/OpenSSL) is a dependency of `MIHCrypto` which seems to have troubles with the `x86_64` architecture. You'd better open an issue on the bug tracker of that repository.

**Comment by hohl** [comment]
Any progress on your issue?

**Comment by aetsyss** [comment]
Have the same problem on Xcode 6.4. Try Xcode 7

**Comment by hohl** [comment]
Should be fixed in release 0.4.1.
