### ISSUE TITLE
RSA encryption using local certificate producing OpenSSL error

### ISSUE THREAD

**Issue by newdev7** [hohl/MIHCrypto#45]
I tried to get the RSA public key (PEM/DER)  from the certificate which stored locally. For getting data from the path, I used the following code.
```
    NSString *publicKeyPath = [[NSBundle mainBundle] pathForResource:@"Public_Certificate" ofType:@"cer"];
    NSData *certData = [NSData dataWithContentsOfFile:publicKeyPath];
```
After I got the data from the path, I tried to get the RSA public key like this.
`MIHRSAPublicKey *key = [[MIHRSAPublicKey alloc] initWithData:certData];`
I'm getting an error in this
```
            if (!PEM_read_bio_PUBKEY(publicBIO, &pkey, NULL, NULL)) {
                @throw [NSException openSSLException];
            }
```
This condition failed and it throws an error. In the console, the error says that

`Terminating app due to uncaught exception 'MIHCryptoException', reason: '[OpenSSL] ERROR: error:0D0680A8:asn1 encoding routines:ASN1_CHECK_TLEN:wrong tag'`

I tried by changing the certificate type also. Tried with pem, der, etc. but for all those certificate types, I'm getting the same error. 

Instead of getting data from path, I'm passed the public key string directly which I got from that data by this code.

`NSString *publicCertificate = [certData base64EncodedStringWithOptions:NSDataBase64EncodingEndLineWithLineFeed];`

The public key string was in this format.

```
NSString *publicCertificate = @"-----BEGIN CERTIFICATE-----"
"..."
"..."
"...="
"-----END CERTIFICATE-----";
NSData *publicStringData = [publicCertificate dataUsingEncoding:NSUTF8StringEncoding];
```
I got the same error.
Tried by converting the string into Base64EncodedString and passed it to MIHRSAKey.

`NSData *data = [[NSData alloc] initWithBase64EncodedString:publicCertificate options:NSDataBase64DecodingIgnoreUnknownCharacters];`

Here I'm getting the data as nil value.
So tried by removing the "---BEGIN CERTIFICATE---" and "---END CERTIFICATE---" from the publicCertificate string and tried. Now I'm getting the data value. But when I passed the data in MIHRASKey, I'm getting the same error.

In MIHRSAKey, I'm getting the base64 data from this code.
```
        NSString *base64DataString = [dataValue MIH_base64EncodedStringWithWrapWidth:64];
        base64DataString = [@"-----BEGIN PUBLIC KEY-----\n" stringByAppendingString:base64DataString];
        base64DataString = [base64DataString stringByAppendingString:@"\n-----END PUBLIC KEY-----"];
        NSData *base64Data = [base64DataString dataUsingEncoding:NSUTF8StringEncoding];
```
When I tried to remove the 'BEGIN PUBLIC KEY' and 'END PUBLIC KEY' line [Since it was already present in my data] and just send it as a base64 encoded data, I got this error.

`Terminating app due to uncaught exception 'MIHCryptoException', reason: '[OpenSSL] ERROR: error:0906D06C:PEM routines:PEM_read_bio:no start line'`

P.S The public certificate was from windows, so I used dos2unix & fold to correct it to *unix file and tested it using **openssl x509 -in certificate.crt -text -noout** . The above error remains the same nevertheless of which certificate I use.

Resolving this error is kind of crucial to me, can anyone please tell me how to resolve this error and successfully encrypt a data using RSA algorithm via MIHCrypto library. 

Thanks.

**Comment by hohl** [comment]
A certificate is not a public key. You're trying to load certificates into the class for public keys which won't work ever, since the class is not designed to work with certificates.

The `--- BEGIN PUBLIC KEY ---` and `--- END PUBLIC KEY ---` are part of the key and must not be removed. However, your certificate doesn't have any public key since it isn't a public. Instead there is `--- BEGIN CERTIFICATE ---` and `--- END CERTIFICATE ---` which - again - ist not the same as a public key.

However, I'm also sorry to tell you that X.509 certificates (that's what your certificate looks like) isn't supported by MIHCrypto yet. Your best bet is to manually extract the public key from the certificate via the OpenSSL command line tools and then try to load the public key via the `MIHRSAPublicKey` class.

**Comment by hohl** [comment]
See also https://github.com/hohl/MIHCrypto/issues/16
