### ISSUE TITLE
RSA key generation seed?

### ISSUE THREAD

**Issue by omerlh** [hohl/MIHCrypto#49]
Hey,
After a quick google search, I find this [SO](http://stackoverflow.com/questions/12089536/how-to-always-generate-different-public-key-using-rsa-generate-key). So I looked in the [manual](https://www.openssl.org/docs/man1.0.2/crypto/RSA_generate_key_ex.html) and seems like the guy is correct and OpenSSL should be seeded before generating keys. My question is - did I understand it correctly? Becuase I looked up and it seems there is no call to RAND_add in this library...
Thanks,
Omer

**Comment by hohl** [comment]
No need to do that, `libCrypto` seeds itself in `RAND_poll`. See this [SO question](http://stackoverflow.com/questions/23854058/how-to-seed-prng-for-usage-with-bn-rand) and the [OpenSSL wiki](https://wiki.openssl.org/index.php/Random_Numbers) for further reading on this topic.

However, for safety purposes, this library checks `RAND_status` to see if seed is prepared before doing anything, so you should be safe. See [MIHInternal.h](https://github.com/hohl/MIHCrypto/blob/master/MIHCrypto/Utils/MIHInternal.m) for more details on the safety check.

**Comment by omerlh** [comment]
ok, thank you!
