### ISSUE TITLE
transitive dependency error while working with cocoapods

### ISSUE THREAD

**Issue by phanisai4u** [hohl/MIHCrypto#51]
The 'Pods' target has transitive dependencies that include static binaries: (/Users/xxx/workspace/xcode/iBBS-Swift/Pods/OpenSSL/lib/libcrypto.a and /Users/xxx/workspace/xcode/iBBS-Swift/Pods/OpenSSL/lib/libssl.a)in

**Comment by hohl** [comment]
duplicate of #40
