### ISSUE TITLE
'openssl/evp.h' file not found

### ISSUE THREAD

**Issue by maxisme** [hohl/MIHCrypto#54]
I am getting the error:

> 'openssl/evp.h' file not found

any idea why it is not there??

**Comment by maxisme** [comment]
`aes.h` is

**Comment by maxisme** [comment]
`bn.h` is also missing

**Comment by maxisme** [comment]
Fixed - set deployment target from 10.8 to 10.9

**Comment by maxisme** [comment]
All files in `openssl` cannot be found. I am file sharing from my MBP to my desktop I think it must be to do with the search paths but they all seem fine. 

It works fine if I copy the files locally and also if I run on the MBP.

**Comment by hohl** [comment]
How did you install MIHCrypto and OpenSSL? Via CocoaPods? The build target version shouldn‘t matter, as long it is above 10.7.

**Comment by maxisme** [comment]
wow thanks for the fast reply. Yes CocoaPods.

**Comment by maxisme** [comment]
in `MIHCrypto` you import `OpenSSL-Universal` like `#import <openssl/*>` which seems weird?

**Comment by hohl** [comment]
Ok, I didn‘t expect that. It sounds like OpenSSL isn‘t setup as a dependency. But CocoaPods does all that for you. So there really shouldn’t be anything you could have done wrong.

Where there any errors when adding the dependcy? Maybe you could try removing/adding the MIHCrypto dependency (to reinstall it).

**Comment by hohl** [comment]
Why is that wired? MIHCrypto is a wrapper for Objective-C build around OpenSSL. That‘s why it also needs OpenSSL as a dependcy. But as said before, CocoaPods setups all the dependencies for you.

**Comment by maxisme** [comment]
god that is awkward. Reinstalled and now working. Thank you

**Comment by hohl** [comment]
Glad you resolved it.
