### ISSUE TITLE
Share and use public and private key

### ISSUE THREAD

**Issue by maxisme** [hohl/MIHCrypto#55]
How could I go about sharing and then using a generated public key?

I have wrote the functions:

```
-(NSString*)keyTo64String:(id)key{
    NSData *key_data = [NSKeyedArchiver archivedDataWithRootObject:key];
    return [key_data base64EncodedStringWithOptions:0];
}

-(id)string64ToKey:(NSString*)key{
    NSData* priv_actual_data = [[NSData alloc] initWithBase64EncodedString:key options:0];
    return [NSKeyedUnarchiver unarchiveObjectWithData:priv_actual_data];
}
```

The first function will return a string representation of the `MIHPublicKey` or `MIHPrivateKey` object.
And the second from the string to the object.

It would be cool if I could export the key in a format similar to a .pem file. It would also be great if I could read that format and turn it back into the object.

How would you recommend doing it?

**Comment by maxisme** [comment]
I have noticed the `dataValue` but what about being able to set this?

**Comment by hohl** [comment]
All keys (symmetric and asymmetric) have a constructor `- initWithData:dataValue`and a getter `dataValue` which work with the raw key values. PEM is just the raw values BASE64 encoded. Have a look at the unit tests in [MIHRSAKeyTests.m](https://github.com/hohl/MIHCrypto/blob/master/MIHCryptoTests/RSA/MIHRSAKeyTests.m) for sample usage with PEM files.

**Comment by maxisme** [comment]
Awesome thank you.

Have you thought about implementing Elliptic Curve technology?

**Comment by hohl** [comment]
Yes, ECC was on my TODO list. But since I never needed it I also never done so.
