### ISSUE TITLE
memory leak found in MIHRSAPrivateKey

### ISSUE THREAD

**Issue by zty0** [hohl/MIHCrypto#60]
<img width="811" alt="Screen Shot 2020-04-30 at 10 24 47 AM" src="https://user-images.githubusercontent.com/9492506/80665897-4e037680-8acd-11ea-82ca-492e21743b24.png">

Is there a reason that this line of code `EVP_PKEY_free(pkey);` is commented?

**Comment by zty0** [comment]
not only pkey is leaked, privateBIO is also leaked in this code

**Comment by hohl** [comment]
Thank you for pointing that out. Looking at the commit history, I am to blame for the uncommented line myself, but as this happened 6 years ago, I have no clue anymore why I did that. Let my quickly check out, whether it would break anything when I uncomment that part, but I guess it is needed by `EVP_PKEY_get1_RSA ` as that seems to only use it by reference.

**Comment by hohl** [comment]
Indeed, `privateBIO` also seems to be leaked a few lines below (in `- (NSData *)dataValue`) too.

**Comment by hohl** [comment]
As `EVP_PKEY_free` does references counting according internally to the [OpenSSL docs](https://www.openssl.org/docs/man1.1.0/man3/EVP_PKEY_free.html) it should be fine to call it in the `@finally` block, so I really can't see why that line was uncommented 6 years ago.

**Comment by zty0** [comment]
I checked source code of Openssl a few hours ago, I think it should be safe to just free `privateBIO` and `pkey` in the `@finally` block.

**Comment by zty0** [comment]
@hohl actually, you only fixed this problem in `MIHRSAPublicKey.m` `MIHRSAPrivateKey.m` has the same problem

**Comment by zty0** [comment]
oh, my bad. I missed the other commit reference. closing the issue
