### ISSUE TITLE
Use ECC encryption to decrypt how to use.

### ISSUE THREAD

**Issue by lvzhao666** [hohl/MIHCrypto#63]

**Comment by hohl** [comment]
ECC support is only available through MIHCrypto version 0.5.0 which is not available through the central Cocoapods directory. To manually install MIHCrypto 0.5.0, run:

```
pod 'MIHCrypto', :git => 'https://github.com/hohl/MIHCrypto.git', :tag => '0.5.0'
```

Then you can find ECC support through the `MIHEC*` classes.
